repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910
  #   hooks:
  #     - id: mypy
  # - repo: https://github.com/pytest-dev/pytest
  #   rev: 6.2.4
  #   hooks:
  #     - id: pytest
