[project]
name = "team8-yotov-template-repository"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.6.11",
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "ruff>=0.9.5",
]

[tool.ruff]
line-length = 88
select = ["E", "F", "W"]
ignore = ["E501"]
