version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv sync
            uv pip install -e .
      - run:
          name: Run Linter
          command: uv run ruff check .
      # - run:
      #     name: Run Type Checker
      #     command: uv run mypy .
      - run:
          name: Run Tests
          command: | 
            export PYTHONPATH="$PYTHONPATH:$PWD"
            uv run pytest --junitxml=test-results/results.xml --cov=src

      - run:
          name: Upload Coverage
          command: uv run coverage xml
      
      - run:
          name: Generate coverage report
          command: uv run coverage report  # Generate a coverage report in the console
          
      - run:
          name: Generate coverage HTML report
          command: uv run coverage html  # Generate an HTML report

      # Store test results to display in CircleCI UI
      # - store_test_results:
      #     path: test-results
      - store_artifacts:
          path: coverage_html_report  # Correct path format
          destination: htmlcov_reports  
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
