version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Create Virtual Environment
          command: uv venv
      - run:
          name: Activate Virtual Environment
          command: source .venv/bin/activate
      - run:
          name: Install ruff with uv
          command: uv pip install ruff
      - run:
          name: Run ruff check
          command: ruff check .
      - run:
          name: Install Dependencies
          command: |
            uv sync
            # Install component packages
            for component in calculator logger notifier; do
              cd $component && uv pip install -e . && cd ..
            done
            # Install main package
            uv pip install -e .
      - run:
          name: Run Linter
          command: uv run ruff check .
      - run:
          name: Run Type Checker
          command: uv run mypy calculator logger notifier tests
      - run:
          name: Run Tests
          command: | 
            export PYTHONPATH="$PYTHONPATH:$PWD"
            uv run pytest --junitxml=test-results/results.xml --cov=calculator --cov=logger --cov=notifier
      - run:
          name: Upload Coverage
          command: uv run coverage xml
      - run:
          name: Generate coverage report
          command: uv run coverage report
      - run:
          name: Generate coverage HTML report
          command: uv run coverage html

      # Store test results to display in CircleCI UI
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: htmlcov
          destination: coverage-report
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
