version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install uv coverage ruff
      - run:
          name: Create virtual environment and install packages
          command: |
            uv venv
            source .venv/bin/activate
            uv pip install -e my_inbox_api
            uv pip install coverage ruff
      - run:
          name: Run linting and formatting check with Ruff
          command: |
            source .venv/bin/activate
            ruff check .
      - run:
          name: Run Tests
          command: | 
            source .venv/bin/activate
            mkdir -p test-results
            pytest . --junitxml=test-results/junit.xml
      - run:
          name: Run Static Analysis mypy
          command: | 
            source .venv/bin/activate
            mypy src tests
      - run:
          name: Generate Coverage Reports
          command: |
            source .venv/bin/activate
            coverage report --fail-under=80 
            coverage xml #Generate XML report
            coverage json -o test-results/coverage.json #Generate JSON report
      - store_test_results:
          path: test-results
      - store_artifacts: 
          path: htmlcov
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report

workflows:
  main:
    jobs:
      - build-and-test
